### ISSUE TITLE
Auth0 Callback

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify-back-end#105]
Issue: callback needs to have a URL that takes the user back to the campaign page they were on before hitting login, currently it takes the user to home 
<img width="848" alt="Screen Shot 2021-08-20 at 12 44 53 PM" src="https://user-images.githubusercontent.com/9143339/130286435-98000c40-e4c2-40f6-9f5d-88c7029513f5.png">
does it have to do with specifying the url path?

BACKGRUOND: 

- backend needs to have those postal codes cached to the user_volunteer table 
- frontend checks the token to see if user signed in to see what to display 

logged in screen:
<img width="480" alt="Screen Shot 2021-08-20 at 12 51 03 PM" src="https://user-images.githubusercontent.com/9143339/130286539-dfb51a7e-fbc8-4a5a-af23-baccd44f3b28.png">

need to log in screen: 
<img width="486" alt="Screen Shot 2021-08-20 at 12 51 32 PM" src="https://user-images.githubusercontent.com/9143339/130286598-1a368728-79f2-4d28-a7fe-3037a99594f9.png">

**Comment by mahrsbar** [comment]
What we need is a **dynamic callback after login** which Auth0 doesn't allow you to specify in the Application Settings. 
Written [here](https://community.auth0.com/t/dynamic-callback-after-login/8788), user suggests 

> There are multiple ways you can accomplish this, for example, you can use the fact that the OAuth 2.0 state parameter is round-tripped back to your client application as way to know the page the end-user was visiting before the login (see The State Parameter 681). In addition, you can just store the current page in application specific storage like a session or web storage and then redirect based on that.

**Comment by BeeXiong** [comment]
[Also found this link: ](https://auth0.com/docs/rules/redirect-users). We talked about how it needs to be in the back end for auth but would still need that dynamic callback.

Just wondering if we can pass state to the back end and then when authenticated pass the state back into the front end. Unsure if this is even possible but wanted to add some context.

**Comment by teakopp** [comment]
Sorry I missed meeting! I saw the invite a little too late. I like the redirect using state. I'm happy to try my hand at a prototype of the state redirect this week. If anyone has already gotten this going, or just needs someone to test something, just let me know 😄

**Comment by BeeXiong** [comment]
A few things to look into after talking @mscoutermarsh 

**Return_to parameter to redirect us**

**Save state via query params**

- Example - Achievable in React (Need to confirm in Vue) 
  - Every time you click a representative have the router update the url to have a query parameter added
  - Every time you land on the page it checks the parameters and returns the page to the correct state using the query parameters

Once login is set then there is a cookie to validate 

**Security**
Pass just the path (after the .com) - Add the base in the back end to avoid letting people redirect you.

**Comment by manishapriya94** [comment]
@teakopp would it be alright to go ahead with a prototype, and is any of the above useful with query params?

**Comment by teakopp** [comment]
An update: I think I've got something that should be easy to implement!.

We can just store url locally as a base64 code, use it as state code, then decode it and redirect directly to decoded url. 

I have some changes to push to my own branch on [amplify-front-end](https://github.com/ProgramEquity/amplify-front-end), that may explain a it a bit better, but I may need to be given write permission to push to branch 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/17583366/131270045-e5aa05c9-7e9a-4164-9b6b-4a6fbd7a129e.png">
