### ISSUE TITLE
API call not working

### ISSUE THREAD

**Issue by mahrsbar** [ProgramEquity/amplify-back-end#122]
The [Letter_Versions API call](https://github.com/ProgramEquity/amplify-back-end/wiki/Letter_Versions-API-Endpoints) is giving me 500 error.

<img width="1439" alt="Screen Shot 2021-10-28 at 2 36 52 PM" src="https://user-images.githubusercontent.com/66452376/139331800-e9bd2bf5-591d-4af7-a7a2-cda1c827836c.png">

**Comment by manishapriya94** [comment]
#123
