### ISSUE TITLE
Error 429 Too Many Requests

### ISSUE THREAD

**Issue by mahrsbar** [ProgramEquity/amplify-back-end#165]
I keep receiving the following error, even though I'm pretty certain I'm not sending too many requests at a time. This error is new and I wasn't receiving it before, I don't think I have changed anything significant for this to occur.

<img width="595" alt="Screen Shot 2022-01-11 at 2 02 01 PM" src="https://user-images.githubusercontent.com/66452376/149021594-d0b28ac5-bbec-440d-acb3-c10659e8beb7.png">

I'm unsure how to navigate this, any help would be appreciated.

**Comment by manishapriya94** [comment]
@teakopp does this have to do with us going public or is it the throttling of Lob?

**Comment by teakopp** [comment]
[PR #166](https://github.com/ProgramEquity/amplify-back-end/pull/166) should fix this 🤞🏻

**Comment by mahrsbar** [comment]
Closed, moved to front-end
