### ISSUE TITLE
Auth0 Set Up

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify-back-end#17]
Creating the URL to direct users to when checking session authentication prior to sending letter. Referencing Rules Layer #19 
- [x] adding to .env
- [x] secret variable in heroku 

**Referencing the Auth0 basic Setup** 
<img width="918" alt="Screen Shot 2021-04-05 at 3 17 48 PM" src="https://user-images.githubusercontent.com/9143339/113633636-26445900-9622-11eb-812c-1127e7e9dcd8.png">

**We have the following setup in Heroku** 
to be referenced in further routing of the user 
https://git.heroku.com/murmuring-headland-63935.git
<img width="356" alt="Screen Shot 2021-04-05 at 3 28 47 PM" src="https://user-images.githubusercontent.com/9143339/113634462-a28b6c00-9623-11eb-95ff-13cd4596f696.png">

**Comment by manishapriya94** [comment]
Hi @teakopp, for frontend @mahrsbar was wondering if we already have the API routed to be used by frontend. Do you just need an empty page or a modal?

**Comment by teakopp** [comment]
@manishapriya94 I haven't finished it, but will hopefully have it done this week 🤞🏻

**Comment by teakopp** [comment]
@manishapriya94 Sorry for delay on this! I got the auth working. It now has the functionality to accept tokens created by front-end. I'll open a PR tomorrow. I just need to finish updated instructions for contributors, as the changes will most likely effect everyone and it'll be good to go.
