### ISSUE TITLE
Secure 'Lint workflows' action

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify-back-end#202]

**Comment by zengwuxin** [comment]
@afcollins would you like to work on this together? I'm new to actions, but interested in learning more and hopefully contribute too

**Comment by zengwuxin** [comment]
- No secrets, scripts are used in the Lint workflows.👍
- CODEOWNERS file has the dev team listed as a required PR approver for all code changes. 👍
- Workflows is not accessing cloud resources, so OpenID connect does not apply. 👍
- Workflows is not using a third-party action.👍
- Do we want this action to scope the frontend repo too? If so, we might want to consider securing cross-repo access with github token.

**Comment by zengwuxin** [comment]
As far as the Amplify App goes, we will combine the frontend and backend repos. Also, github token almost always only works within a single repo.
