### ISSUE TITLE
2. User Authentication

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify-back-end#6]
# Use Case
User authenticates through email in order to send campaign later (limit spam).  Store their information into a database on airtable to be indexed for each campaign letter 
<img width="1186" alt="Screen Shot 2021-01-30 at 1 45 47 AM" src="https://user-images.githubusercontent.com/9143339/106444869-51f16a00-644c-11eb-8911-c5aa838e7e65.png">

## Background info
- [passport-google-oauth](http://www.passportjs.org/packages/passport-google-oauth)

## Implementation
- [x] vue + express + node set up @BeeXiong 
- [x] creating crm in airtable @manishapriya94 
- [ ] [setting up airtable as a database ](https://dev.to/rizkyrajitha/using-airtable-as-a-database-421d) 
- [ ] [passport authentication](https://www.youtube.com/watch?v=6FOq4cUdH8k)

**Comment by manishapriya94** [comment]
Wanted to address setting airtable as a database? @BeeXiong 
1. Should we go for mongodb [(would work with Passport) ](https://www.youtube.com/watch?v=6FOq4cUdH8k)
2. Should we go for serverless for Fire Torch [(Firebase)](https://firebase.google.com/docs/web/setup)
- How does this affect the cross referencing for user with voter registration in the future? 
- How does this affect the cross referencing for campaigns/letters sent in distribute airtable

There are 2 versions of how we can authenticate users @ankitagrawal98 
1. [Passport with MongoDB](https://www.youtube.com/watch?v=6FOq4cUdH8k)
2. [Firebase + Vue Serverless](https://dev.to/thisdotmedia/firebase-for-user-authentication-in-vue-js-ebn)
  - [For reference: will have to install this into npm  ](https://github.com/firebase/firebaseui-web#installation)

**Comment by BeeXiong** [comment]
I think this depends on where we want the work done. 

### If people feel comfortable with Vue then we can go firebase.
- _More code on the front end so we need to be comfortable with Vue syntax._  

### If we want to keep the work on the back end we go Passport + Mongo
- _Probably got more people familiar with express/node.js_ 

### Some thoughts on the other questions...
 > How does this affect the cross referencing for user with voter registration in the future?
- Looked like it was pretty easy to associate data to user ID's in Firebase and would probably be the same for Mongo. Solves ❓ below ⏫  

> How does this affect the cross referencing for campaigns/letters sent in distribute airtable
- I think we need to standardize on something so we can set up that relational aspect. I'm thinking it will be a nightmare to have to go between two data sources. 

I think I'd prefer Firebase Authentication + Cloud Firestore (DB) together is nice 👍 but it does impact your workflow with airtable too @manishapriya94 

Thoughts???

**Comment by teakopp** [comment]
Hi @manishapriya94 

Sorry for the super late reply 😅 

If the plan is to keep the project in Heroku, I would recommend a Postgres/MySQL DB. In my experience, MongoDB has been huge pain to setup in Heroku. Also, I believe the Heroku add-on costs extra $$$.

I've never used Firebase, but it seems pretty cool. I'm a fan of passport. I use it pretty regularly and the setup is usually pretty simple.

**Comment by mscoutermarsh** [comment]
I'd recommend going with the boring postgres or mysql approach also. It doesn't scale as nicely as firebase. But, you'd be very successful if you got to that point of it ever being a problem.

Being relational would be the big win. Easier to associate data with other data.
